/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as signRouteRouteImport } from './routes/(sign)/route'
import { Route as authenticatedRouteRouteImport } from './routes/(authenticated)/route'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as signSignUpRouteImport } from './routes/(sign)/sign-up'
import { Route as signSignInRouteImport } from './routes/(sign)/sign-in'
import { Route as publicGoodbyeRouteImport } from './routes/(public)/goodbye'
import { Route as authenticatedOnboardingIndexRouteImport } from './routes/(authenticated)/onboarding/index'
import { Route as authenticatedOnboardingSetupProfileRouteImport } from './routes/(authenticated)/onboarding/setup-profile'
import { Route as authenticatedOnboardingCompleteRouteImport } from './routes/(authenticated)/onboarding/complete'
import { Route as authenticatedappHomeRouteImport } from './routes/(authenticated)/(app)/home'
import { Route as authenticatedappSettingsAccountProfileRouteImport } from './routes/(authenticated)/(app)/settings/account/profile'
import { Route as authenticatedappSettingsAccountPreferencesRouteImport } from './routes/(authenticated)/(app)/settings/account/preferences'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const signRouteRoute = signRouteRouteImport.update({
  id: '/(sign)',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedRouteRoute = authenticatedRouteRouteImport.update({
  id: '/(authenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/(public)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const signSignUpRoute = signSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => signRouteRoute,
} as any)
const signSignInRoute = signSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => signRouteRoute,
} as any)
const publicGoodbyeRoute = publicGoodbyeRouteImport.update({
  id: '/(public)/goodbye',
  path: '/goodbye',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedOnboardingIndexRoute =
  authenticatedOnboardingIndexRouteImport.update({
    id: '/onboarding/',
    path: '/onboarding/',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedOnboardingSetupProfileRoute =
  authenticatedOnboardingSetupProfileRouteImport.update({
    id: '/onboarding/setup-profile',
    path: '/onboarding/setup-profile',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedOnboardingCompleteRoute =
  authenticatedOnboardingCompleteRouteImport.update({
    id: '/onboarding/complete',
    path: '/onboarding/complete',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedappHomeRoute = authenticatedappHomeRouteImport.update({
  id: '/(app)/home',
  path: '/home',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authenticatedappSettingsAccountProfileRoute =
  authenticatedappSettingsAccountProfileRouteImport.update({
    id: '/(app)/settings/account/profile',
    path: '/settings/account/profile',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedappSettingsAccountPreferencesRoute =
  authenticatedappSettingsAccountPreferencesRouteImport.update({
    id: '/(app)/settings/account/preferences',
    path: '/settings/account/preferences',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/goodbye': typeof publicGoodbyeRoute
  '/sign-in': typeof signSignInRoute
  '/sign-up': typeof signSignUpRoute
  '/': typeof publicIndexRoute
  '/home': typeof authenticatedappHomeRoute
  '/onboarding/complete': typeof authenticatedOnboardingCompleteRoute
  '/onboarding/setup-profile': typeof authenticatedOnboardingSetupProfileRoute
  '/onboarding/': typeof authenticatedOnboardingIndexRoute
  '/settings/account/preferences': typeof authenticatedappSettingsAccountPreferencesRoute
  '/settings/account/profile': typeof authenticatedappSettingsAccountProfileRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/goodbye': typeof publicGoodbyeRoute
  '/sign-in': typeof signSignInRoute
  '/sign-up': typeof signSignUpRoute
  '/': typeof publicIndexRoute
  '/home': typeof authenticatedappHomeRoute
  '/onboarding/complete': typeof authenticatedOnboardingCompleteRoute
  '/onboarding/setup-profile': typeof authenticatedOnboardingSetupProfileRoute
  '/onboarding': typeof authenticatedOnboardingIndexRoute
  '/settings/account/preferences': typeof authenticatedappSettingsAccountPreferencesRoute
  '/settings/account/profile': typeof authenticatedappSettingsAccountProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(authenticated)': typeof authenticatedRouteRouteWithChildren
  '/(sign)': typeof signRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/(public)/goodbye': typeof publicGoodbyeRoute
  '/(sign)/sign-in': typeof signSignInRoute
  '/(sign)/sign-up': typeof signSignUpRoute
  '/(public)/': typeof publicIndexRoute
  '/(authenticated)/(app)/home': typeof authenticatedappHomeRoute
  '/(authenticated)/onboarding/complete': typeof authenticatedOnboardingCompleteRoute
  '/(authenticated)/onboarding/setup-profile': typeof authenticatedOnboardingSetupProfileRoute
  '/(authenticated)/onboarding/': typeof authenticatedOnboardingIndexRoute
  '/(authenticated)/(app)/settings/account/preferences': typeof authenticatedappSettingsAccountPreferencesRoute
  '/(authenticated)/(app)/settings/account/profile': typeof authenticatedappSettingsAccountProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/goodbye'
    | '/sign-in'
    | '/sign-up'
    | '/'
    | '/home'
    | '/onboarding/complete'
    | '/onboarding/setup-profile'
    | '/onboarding/'
    | '/settings/account/preferences'
    | '/settings/account/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/goodbye'
    | '/sign-in'
    | '/sign-up'
    | '/'
    | '/home'
    | '/onboarding/complete'
    | '/onboarding/setup-profile'
    | '/onboarding'
    | '/settings/account/preferences'
    | '/settings/account/profile'
  id:
    | '__root__'
    | '/(authenticated)'
    | '/(sign)'
    | '/login'
    | '/(public)/goodbye'
    | '/(sign)/sign-in'
    | '/(sign)/sign-up'
    | '/(public)/'
    | '/(authenticated)/(app)/home'
    | '/(authenticated)/onboarding/complete'
    | '/(authenticated)/onboarding/setup-profile'
    | '/(authenticated)/onboarding/'
    | '/(authenticated)/(app)/settings/account/preferences'
    | '/(authenticated)/(app)/settings/account/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authenticatedRouteRoute: typeof authenticatedRouteRouteWithChildren
  signRouteRoute: typeof signRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  publicGoodbyeRoute: typeof publicGoodbyeRoute
  publicIndexRoute: typeof publicIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(sign)': {
      id: '/(sign)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof signRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)': {
      id: '/(authenticated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(sign)/sign-up': {
      id: '/(sign)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof signSignUpRouteImport
      parentRoute: typeof signRouteRoute
    }
    '/(sign)/sign-in': {
      id: '/(sign)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof signSignInRouteImport
      parentRoute: typeof signRouteRoute
    }
    '/(public)/goodbye': {
      id: '/(public)/goodbye'
      path: '/goodbye'
      fullPath: '/goodbye'
      preLoaderRoute: typeof publicGoodbyeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/onboarding/': {
      id: '/(authenticated)/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof authenticatedOnboardingIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/onboarding/setup-profile': {
      id: '/(authenticated)/onboarding/setup-profile'
      path: '/onboarding/setup-profile'
      fullPath: '/onboarding/setup-profile'
      preLoaderRoute: typeof authenticatedOnboardingSetupProfileRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/onboarding/complete': {
      id: '/(authenticated)/onboarding/complete'
      path: '/onboarding/complete'
      fullPath: '/onboarding/complete'
      preLoaderRoute: typeof authenticatedOnboardingCompleteRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/(app)/home': {
      id: '/(authenticated)/(app)/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof authenticatedappHomeRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/(app)/settings/account/profile': {
      id: '/(authenticated)/(app)/settings/account/profile'
      path: '/settings/account/profile'
      fullPath: '/settings/account/profile'
      preLoaderRoute: typeof authenticatedappSettingsAccountProfileRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/(app)/settings/account/preferences': {
      id: '/(authenticated)/(app)/settings/account/preferences'
      path: '/settings/account/preferences'
      fullPath: '/settings/account/preferences'
      preLoaderRoute: typeof authenticatedappSettingsAccountPreferencesRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
  }
}

interface authenticatedRouteRouteChildren {
  authenticatedappHomeRoute: typeof authenticatedappHomeRoute
  authenticatedOnboardingCompleteRoute: typeof authenticatedOnboardingCompleteRoute
  authenticatedOnboardingSetupProfileRoute: typeof authenticatedOnboardingSetupProfileRoute
  authenticatedOnboardingIndexRoute: typeof authenticatedOnboardingIndexRoute
  authenticatedappSettingsAccountPreferencesRoute: typeof authenticatedappSettingsAccountPreferencesRoute
  authenticatedappSettingsAccountProfileRoute: typeof authenticatedappSettingsAccountProfileRoute
}

const authenticatedRouteRouteChildren: authenticatedRouteRouteChildren = {
  authenticatedappHomeRoute: authenticatedappHomeRoute,
  authenticatedOnboardingCompleteRoute: authenticatedOnboardingCompleteRoute,
  authenticatedOnboardingSetupProfileRoute:
    authenticatedOnboardingSetupProfileRoute,
  authenticatedOnboardingIndexRoute: authenticatedOnboardingIndexRoute,
  authenticatedappSettingsAccountPreferencesRoute:
    authenticatedappSettingsAccountPreferencesRoute,
  authenticatedappSettingsAccountProfileRoute:
    authenticatedappSettingsAccountProfileRoute,
}

const authenticatedRouteRouteWithChildren =
  authenticatedRouteRoute._addFileChildren(authenticatedRouteRouteChildren)

interface signRouteRouteChildren {
  signSignInRoute: typeof signSignInRoute
  signSignUpRoute: typeof signSignUpRoute
}

const signRouteRouteChildren: signRouteRouteChildren = {
  signSignInRoute: signSignInRoute,
  signSignUpRoute: signSignUpRoute,
}

const signRouteRouteWithChildren = signRouteRoute._addFileChildren(
  signRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authenticatedRouteRoute: authenticatedRouteRouteWithChildren,
  signRouteRoute: signRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  publicGoodbyeRoute: publicGoodbyeRoute,
  publicIndexRoute: publicIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
